spring:
  rabbitmq:
    host: 192.168.7.130  # 172.16.121.145  / 192.168.7.130
    port: 5672
    username: lishuai
    password: lishuai
    virtual-host: /sbt
    publisher-confirms: true
    publisher-returns: true
